---
- name: drop controlplane-vip static manifest
  template:
    dest: /etc/kubernetes/manifests/kubernetes-vip.yaml
    src: etc/kubernetes/manifests/kubernetes-vip.yaml
  when: inventory_hostname in groups['masters']

- name: update /etc/hosts to include cluster fqdn
  lineinfile:
    dest: /etc/hosts
    line: "{{ kubernetesVip_ip }} {{ kubernetesVip_fqdn }}"
    state: present
  tags: 
    - init
    - initMaster