---
- name: add the kubernetes apt repo key
  apt_key:
    url: "{{ kubernetes_aptKeyUrl }}"
    state: present

- name: add the kubernetes apt repo
  apt_repository:
    repo: "{{ kubernetes_aptRepo }}"
    update_cache: True
    state: present

- name: install kubernetes packages
  apt:
    name: "{{ item }}"
  with_items:
    - "kubelet={{ kubernetes_version | kube_platform_version('debian') }}"
    - "kubeadm={{ kubernetes_version | kube_platform_version('debian') }}"
    - "kubectl={{ kubernetes_version | kube_platform_version('debian') }}"
    - "kubernetes-cni={{ kubernetes_cni_version | kube_platform_version('debian') }}"
