---

- name: "checks if {{ package }} binary is manually provided"
  stat: 
    path: "/vagrant/bin/packages/{{ package }}"
  register: b

- name: "overrides {{ package }} binary from .deb package with {{ package }} binary from local filesystem"
  copy: 
    remote_src: True 
    src: "/vagrant/bin/packages/{{ package }}"
    dest: "/usr/bin/{{ package }}"
    mode: 0755
  when: b.stat.exists is defined and b.stat.exists  
