---

- name: check if kubeadm join already done
  stat: path=/etc/kubernetes/join.done
  register: p

- name: Set kubeadmJoin_url
  set_fact:  
    kubeadmJoin_url: "{% if groups['masters'] | length > 1 %}{{ kubeadmJoin_fqdn }}{% else %}{{ hostvars[groups['masters'][0]]['node_ip'] }}{% endif %}"

- name: join nodes to masters
  command: "{{ kubeadmJoin_binary }} join {{ kubeadmJoin_url }}:6443 --token='{{ kubeadmJoin_token }}' --discovery-token-unsafe-skip-ca-verification"
  when: p.stat.exists is defined and not p.stat.exists

- name: mark join done
  file: path=/etc/kubernetes/join.done state=touch owner=root group=sys mode=0555
  when: p.stat.exists is defined and not p.stat.exists