---
- name: update apt cache
  apt:
    update_cache: True
    cache_valid_time: 3600

- name: perform a dist-upgrade
  apt:
    upgrade: dist
  when: common_upgrade | bool

- name: install baseline dependencies for debian
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ebtables
    - socat
    - ntp
    - python-pip
    - python-requests
