---

- name: computes etcd client endpoints
  set_fact:
    etcd_client_endpoints: "{{ groups['etcds']|map('extract', hostvars, ['node_ip'])|map('regex_replace', '^(.*)$', 'http://\\1:2379')|list|sort }}"
  when: "'etcds' in group_names and groups['etcds'] | length > 1"

- name: gets the kubeadm version
  command: "{{ kubeadmConfig_binary }} version -o short"
  register: kubeadm_output

- name: sets kubeadm api version to v1alpha1
  set_fact:
    kubeadmConfig_api_version: v1alpha1
  when: kubeadmConfig_api_version=='' and kubeadm_output.stdout | semverlt('v1.11.0-a') # nb. in kubelet >= v1.11.* v1alpha2 is used

- name: defaults kubeadm api version to v1alpha2
  set_fact:
    kubeadmConfig_api_version: v1alpha2
  when: kubeadmConfig_api_version==''

- name: create /etc/kubernetes directory
  file:
    dest: "/etc/kubernetes"
    state: directory

- name: drop kubeadm template
  template:
    src: "etc/kubernetes/kubeadm.conf.{{ kubeadmConfig_api_version }}.yaml.j2"
    dest: /etc/kubernetes/kubeadm.conf
