---

- name: create kubernetes config directory
  file:
    dest: "/home/vagrant/.kube/"
    state: directory
    group: vagrant
    owner: vagrant
    mode: 0770

- name: copy kubernetes config to home directory
  command: "cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config"

- name: set config permissions
  file:
    dest: "/home/vagrant/.kube/config"
    state: file
    group: vagrant
    owner: vagrant
    mode: 0660
